GRANT DATABASE ROLE SNOWFLAKE.USAGE_VIEWER TO ROLE DBT_DEVELOPER;
GRANT DATABASE ROLE SNOWFLAKE.GOVERNANCE_VIEWER TO ROLE DBT_DEVELOPER;
GRANT DATABASE ROLE SNOWFLAKE.OBJECT_VIEWER TO ROLE DBT_DEVELOPER;
GRANT DATABASE ROLE SNOWFLAKE.SECURITY_VIEWER TO ROLE DBT_DEVELOPER;


-- Incoming 
show grants  to role DBT_DEVELOPER;
-- Outgoing
show grants  on role DBT_DEVELOPER;
-- database roles 
show grants  to database role SNOWFLAKE.USAGE_VIEWER;




GRANT IMPORTED PRIVILEGES
ON DATABASE SNOWFLAKE
TO ROLE DBT_DEVELOPER;


grant monitor on account to role dbt_developer;


revoke IMPORTED PRIVILEGES
ON DATABASE SNOWFLAKE
FROM ROLE DBT_DEVELOPER;

REVOKE monitor on account from role dbt_developer;

show grants on role dbt_developer;