snowdbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: SOLDER
      role: dbt_developer
      database: SNOWDBT_DEV
      schema: dev
      warehouse: DWH
    prod:
      type: snowflake
      account: 'not needed'
      user: SOLDIER
      role: dbt_developer
      database: SNOWDBT_PROD
      schema: prod
      warehouse: DWH