USE WAREHOUSE DWH;
select * from SNOWFLAKE_SAMPLE_DATA.TPCH_SF10000.CUSTOMER limit 10;


SELECT warehouse_name,sum(credits_used_compute),sum(CREDITS_USED_CLOUD_SERVICES)
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY 
group by all;


SELECT *
  FROM SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_ROLES;